### ISSUE TITLE
compilation terminated

### ISSUE THREAD

**Issue by stella-cheng21** [Hydran00/UR5e-Unity-simulator-ROS-connection#1]
When I execute the first step, there's an error occured:
    **fatal error**:scrabble/PutTile.h : There is no file or directory for that.
Cause I'm a newer to coding, I wonder if you forgot to upload the file or I have to write it by my own. I really appreciate if u can tell me how to fix the problem.
   Thank u sooooo much!!! Hope u have a good day!!!

**Comment by Hydran00** [comment]
Hi, thank you for the interested in the project. Unfortunately, I switched to ROS2 just after completing this project, so I suggest you the same since it is more supported and there's better documentation. Anyway I think I forgot to remove `scrabble_robot_control.cpp` from the repository (it was related to another project) so probably you can just remove that file, and comment the relative CMake compilation directives (i.e. `add_executable(scrabble_robot_control_node src/scrabble_robot_control.cpp` and  `target_link_libraries(scrabble_robot_control_node
   ${catkin_LIBRARIES}`
 )) . If this does not help, let me know and I'll investigate as far as I have a little time.

Have a good day :)

**Comment by stella-cheng21** [comment]
Thank you so much for your sincere reply and suggestion! Due to the time lag, I'm sorry that I didn't reply to you at the first time. The problem has been solved~ Cause I'm studying communicating ros and unity so your project helps a lot and I can continue to study your project(*^▽^*)  
Would you mind to recommending some online study materials to me if there are any? Hope i don't bother u :)

**Comment by stella-cheng21** [comment]
I do have another problem. When i open the project in unity, errors occured like this :
**The type or namespace 'EigenCore' could not be found (are you missing a using directive or an assembly reference?)**
**The type or namespace 'MatrixXD' could not be found (are you missing a using directive or an assembly reference?)**
I don't know if there is a problem with the configuration file or something else, could u give some inspiration or the unity version？

**Comment by Hydran00** [comment]
If you are looking for online material for the Unity Robotics Hub, there isn' t much so you must rely on the README in their repository. For tutorials on ROS2, the official documentation is really well done. For both ROS1 and ROS2 there are good tutorial also in roboticscasual.com

**Comment by Hydran00** [comment]
For the error you are getting I am not sure but usually It Is related to the assembly definition file (asmdef) in which you have to tick the architecture you want to build for. In this project I was computing the UR5e inverse kinematics directly on the Oculus, that is why I used [this](https://github.com/modios/EigenCore) wrapper for Eigen. I remember that I had some problems with the package itself but I do not remember the solutions. Anyway, from my experience, I would suggest you to compute the kinematics in the host PC directly and use the Oculus just for the visualisation part, in this way you reduce the computational requirements of your app and improve safety. For example you should publish from the Oculus just the target position to the host PC and read from the host the current robot position. In this way you also avoid compiling the Eigen wrapper and the setup becomes faster and easier. Hope this helps.

**Comment by stella-cheng21** [comment]
I see. Thanks a lot! That's all my problems. Hope u make good progress in your studies and scientific research!
（a student from China ^_^）
